resources:
  - github.com/ironcore-dev/ironcore-net/config/etcdless?ref=324c97f7fc8f982295506c5ea8122d70149e468e

images:
  - name: apiserver
    newName: ghcr.io/ironcore-dev/ironcore-net/apiserver
    newTag: sha-324c97f
  - name: controller:latest
    newName: ghcr.io/ironcore-dev/ironcore-net/controller-manager
    newTag: sha-324c97f

patches:
  - path: patch-apiserver-deployment.yaml
  - path: patch-apiserver-service.yaml
