apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/ironcore-net/config/metalnetlet/kind?ref=324c97f7fc8f982295506c5ea8122d70149e468e

images:
  - name: metalnetlet
    newName: ghcr.io/ironcore-dev/ironcore-net/metalnetlet
    newTag: sha-324c97f

patches:
  - path: patch-deployment.yaml
  - path: add-manager-args.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      namespace: metalnetlet-system
      name: metalnetlet-controller-manager
