apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/ironcore-net/config/apinetlet/kind?ref=324c97f7fc8f982295506c5ea8122d70149e468e

images:
  - name: apinetlet
    newName: ghcr.io/ironcore-dev/ironcore-net/apinetlet
    newTag: sha-324c97f

patches:
  - path: patch-deployment.yaml
