apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/ironcore-net/config/apinetlet/kind?ref=v0.4.1

images:
  - name: apinetlet
    newName: ghcr.io/ironcore-dev/ironcore-net/apinetlet
    newTag: v0.4.1

patches:
  - path: patch-deployment.yaml
