apiVersion: v1
kind: ConfigMap
metadata:
  name: supported-machine-classes
  namespace: libvirt-provider-system
data:
  supported-machine-classes.yaml: |-
    - apiVersion: compute.ironcore.dev/v1alpha1
      kind: MachineClass
      metadata:
        name: t3-small
      capabilities:
        cpu: "2"
        memory: 2Gi
