apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/libvirt-provider/config/default?ref=v0.4.0
  - role-binding.yaml
  - role.yaml

images:
  - name: machinepoollet
    newName: ghcr.io/ironcore-dev/ironcore-machinepoollet
    newTag: v0.4.3
  - name: libvirt-provider
    newName: ghcr.io/ironcore-dev/libvirt-provider
    newTag: v0.4.0

patches:
  - path: patch-manager-daemonset.yaml
